### ISSUE TITLE
Unhandled error in the spdy agent

### ISSUE THREAD

**Issue by loris** [cloudflare/node-cloudflare#22]
Hi, we updated to the lastest 2.1.0 release, and had a server crash in one of our API calls to Cloudflare. Here is the stacktrace:

```
throw er; // Unhandled 'error' event Exception
^
Error: Can't send request after GOAWAY Exception
at Connection.reserveStream (/app/node_modules/spdy-transport/lib/spdy-transport/connection.js:614:15)
at Agent._createStream (/app/node_modules/spdy/lib/spdy/agent.js:242:27)
at Handle.<anonymous> (/app/node_modules/spdy/lib/spdy/agent.js:198:29)
at Object.onceWrapper (events.js:314:30)
at emitNone (events.js:105:13)
at Handle.emit (events.js:207:7)
at ClientRequest.send [as _send] (/app/node_modules/spdy/lib/spdy/handle.js:156:10)
at ClientRequest.end (_http_outgoing.js:780:16)
at EventEmitter.ee.on.req (/app/node_modules/got/index.js:100:8)
at emitOne (events.js:115:13)
at EventEmitter.emit (events.js:210:7)
at Immediate.setImmediate [as _onImmediate] (/app/node_modules/got/index.js:81:7)
at runCallback (timers.js:800:20)
at tryOnImmediate (timers.js:762:5)
at processImmediate [as _immediateCallback] (timers.js:733:5)
```

I've been looking for a way to catch that error on our side, but it looks like it is not possible. The options passed to `got` and more specifically the `spdy` agent are hard-coded in your library.
Any idea on that kind of error and how to properly handle it? It looks like some event listeners are missing somewhere in the dep chain (https://github.com/spdy-http2/node-spdy/issues/282).
Thanks

**Comment by loris** [comment]
In the meantime, I think it would be great to allow disabling http2 by changing:

```
  constructor: function (auth) {
    var client = new Client({
      email: auth && auth.email,
      key: auth && auth.key,
      h2: true
    });
```
to something like this:
```
  constructor: function (opts) {
    var client = new Client({
      email: opts && opts.email,
      key: opts && opts.key,
      h2: opts && opts.h2 !== undefined ? opts.h2 : true
    });
```

**Comment by loris** [comment]
To add more context, it looks like it always throws that error on my hosting provider: Heroku, but it works on my local machine. Reverting to `1.1.1` for now.

**Comment by terinjokes** [comment]
I may decide to allow disabling HTTP2, but I'd rather prefer not. Can you tell me how you're using this from Heroku so I can investigate?

**Comment by terinjokes** [comment]
@loris With HTTP2 being worked on in core, I've pulled out the support in this module.

**Comment by loris** [comment]
@terinjokes thanks a lot, sure `2.1.1` works like a charm

**Comment by terinjokes** [comment]
@loris Great. Now I just need to sit down and support the other endpoints :)
