### ISSUE TITLE
TypeError: Cannot set property '_got' of undefined

### ISSUE THREAD

**Issue by kiddyfurby** [cloudflare/node-cloudflare#25]
> // right after initializing cf with my login and key
> cf.zones.browse().then(function (resp) {
>   return resp.result.status;
> });

/root/cf2/node_modules/cloudflare/index.js:48
    this._got = function (endpoint, options) {
              ^

TypeError: Cannot set property '_got' of undefined
    at constructor (/root/cf2/node_modules/cloudflare/index.js:48:15)
    at Object.<anonymous> (/root/cf2/i2.js:2:31)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by terinjokes** [comment]
Can you try updating to version 2 of the `cloudflare` module?

**Comment by kiddyfurby** [comment]
That fixed it for me.  Thank you!
I wonder why I didn't have version 2, I npm install-ed it only a few days ago.
