### ISSUE TITLE
API Token issue

### ISSUE THREAD

**Issue by wesleymilan** [cloudflare/node-cloudflare#48]
I'm using the basic example you gave on this repo, using API token and it's returning the following error:

```
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "x-auth-key"
    at ClientRequest.setHeader (_http_outgoing.js:473:3)
    at new ClientRequest (_http_client.js:194:14)
    at Object.request (https.js:289:10)
    at Object.request (/Users/wesleymilan/Documents/Servers/havasupai-docker/www/workers/firewall/node_modules/agent-base/patch-core.js:25:22)
    at get (/Users/wesleymilan/Documents/Servers/havasupai-docker/www/workers/firewall/node_modules/got/index.js:33:18)
    at requestAsEventEmitter (/Users/wesleymilan/Documents/Servers/havasupai-docker/www/workers/firewall/node_modules/got/index.js:85:2)
    at Promise (/Users/wesleymilan/Documents/Servers/havasupai-docker/www/workers/firewall/node_modules/got/index.js:91:14)
    at new Promise (<anonymous>)
    at asPromise (/Users/wesleymilan/Documents/Servers/havasupai-docker/www/workers/firewall/node_modules/got/index.js:90:9)
    at got (/Users/wesleymilan/Documents/Servers/havasupai-docker/www/workers/firewall/node_modules/got/index.js:302:10)
```

When using API key everything works fine

**Comment by terinjokes** [comment]
What version of `cloudflare` are you using? Support for tokens was added in 2.6.0.

**Comment by naseemkullah** [comment]
Hi I am running into the same issue, I realized it is still install `2.5.1` from npm. Will `2.6.0` be made available on npm @terinjokes ?

**Comment by terinjokes** [comment]
It is available. `npm install cloudflare@2.6.0`

**Comment by naseemkullah** [comment]
Ok thanks, but it is weird that `npm i cloudflare` does not pick that one up automatically today right?

**Comment by naseemkullah** [comment]
![image](https://user-images.githubusercontent.com/24660299/63563345-c7a29800-c52e-11e9-88a8-059ac6ba8f07.png)

**Comment by terinjokes** [comment]
`npm dist-tag ls cloudflare`

**Comment by naseemkullah** [comment]
Thanks for the command, I ran it and the output was:
```
latest-1: 1.1.1
latest: 2.5.1
next: 2.6.0
```

I am under the impression that the latest version is `2.6.0` and that the next would be either `2.6.1`, `2.7.0` or `3.0.0`

**Comment by terinjokes** [comment]
The lastest promoted version is 2.5.1. The next version slated to be promoted is 2.6.0, but might not be promoted in favor of a later version.

These are tiered so that releasing a new, but broken, version oesn't immediately break everyone using it.

You attempted to use a feature from 2.6.0 whilst having 2.5.1 installed.

**Comment by naseemkullah** [comment]
Ah I see, so in general, if a major or minor update comes out, it will not be immediately promoted, and only installable explicitly. 

I would argue that one can use `~2.5.1`  or `2.5.1` syntax  in `package.json` if they so wish and having github and npm latest release align would make more sense. My 2 cents.

And yes indeed I did!
