### ISSUE TITLE
Bad request (400) when zone.add'ing a domain

### ISSUE THREAD

**Issue by JeffSpies** [cloudflare/node-cloudflare#64]
I'm getting the following error:

```
    ErrorClass [HTTPError]: Response code 400 (Bad Request)
      at ~/cloudflare/node_modules/got/index.js:123:13
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
      host: 'api.cloudflare.com',
      hostname: 'api.cloudflare.com',
      method: 'POST',
      path: '/client/v4/zones',
      statusCode: 400,
      statusMessage: 'Bad Request'
    }
```

while `cf.zones.browse` works fine, the following code does not:

```typescript
import CF from 'cloudflare'

// And in an async function
async function main() {
  const cf = CF({
    email: process.env.EMAIL,
    key: process.env.KEY
  })
  try {
    await cf.zones.add({
      account: {
        id: process.env.ACCOUNT_ID
      },
      name: 'example.com',
      jump_start: true
    })
  } catch (error) {
    console.error(error)
  }
}

main()
```

I may be missing something obvious, so help would be appreciated. ~~I tried CURL as well with no success~~ (EDIT: CURL does indeed work). Thanks!

**Comment by vivekkairi** [comment]
Facing same issue

**Comment by vivekkairi** [comment]
@terinjokes  Kindly look into it once.

**Comment by bugs181** [comment]
@JeffSpies out of curiosity, have you tried removing the `account` object? I'm not sure if `edit` follows the same parameter convention as `add` but this is what works for me with `edit`

```js

await cf.dnsRecords.edit(zoneInfo.id, nsRecord.id, {
  type: 'A',
  name: nsRecord.name,
  content: IP,
  ttl: 1,
  proxied: false,
}) 

```

**Comment by terinjokes** [comment]
This code works for me. Be sure to investigate the error message from the Cloudflare API, which is available in `error.response.body`;
